// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pphutuurgbvpluqjpfxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwaHV0dXVyZ2J2cGx1cWpwZnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzE1NTksImV4cCI6MjA3MzM0NzU1OX0.JEjg4WuFolVUVckJyVzUMVR7zqAX9fodly3bfkSHSec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});